POST http://localhost:6543/api/v1/users/login
Content-Type: application/json 

{
    "email": "zeinaboy@gmail.com",
    "password": "ecommerce1"
}

### 

GET http://localhost:6543/api/v1/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcxOTE2MzY0MCwiZXhwIjoxNzE5MTY3MjQwfQ.5q424v1Fo8pt7IHotysVzxoMA9Pt9qbkbuNirTKZp3s

### 

GET http://localhost:6543/api/v1/products 

###

POST http://localhost:6543/api/v1/cart/addToCart 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcxOTE2MzY0MCwiZXhwIjoxNzE5MTY3MjQwfQ.5q424v1Fo8pt7IHotysVzxoMA9Pt9qbkbuNirTKZp3s

{
    "id": 12,
    "quantity": "10"
}

###

POST http://localhost:6543/api/v1/cart/addToCart 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcxOTE2MzY0MCwiZXhwIjoxNzE5MTY3MjQwfQ.5q424v1Fo8pt7IHotysVzxoMA9Pt9qbkbuNirTKZp3s


{
    "id": 6,
    "quantity": 99
}

###

DELETE http://localhost:6543/api/v1/cart/removeFromCart/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcxOTE2MzY0MCwiZXhwIjoxNzE5MTY3MjQwfQ.5q424v1Fo8pt7IHotysVzxoMA9Pt9qbkbuNirTKZp3s

### 
PUT http://localhost:6543/api/v1/cart/updateQuantity
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcxOTE2MzY0MCwiZXhwIjoxNzE5MTY3MjQwfQ.5q424v1Fo8pt7IHotysVzxoMA9Pt9qbkbuNirTKZp3s

{
    "id": 9,
    "newQuantity": 1
}   

###
put http://localhost:6543/api/v1/account/changePassword
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcxOTE2MzY0MCwiZXhwIjoxNzE5MTY3MjQwfQ.5q424v1Fo8pt7IHotysVzxoMA9Pt9qbkbuNirTKZp3s

{
    "password": "ecommerce",
    "newPassword": "ecommerce1"
}

### 
GET http://localhost:6543/api/v1/checkout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcxOTE2MzY0MCwiZXhwIjoxNzE5MTY3MjQwfQ.5q424v1Fo8pt7IHotysVzxoMA9Pt9qbkbuNirTKZp3s

